# Generated by Django 3.2.7 on 2021-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='pseudo',
            new_name='user_name',
        ),
    ]
