# Generated by Django 4.2.2 on 2023-06-25 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_act_token_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.TextField(default=uuid.UUID('7173d17f-25b2-416a-a0fc-bdbb513fcb59'), max_length=500, verbose_name='act_token'),
        ),
    ]
