# Generated by Django 4.2.2 on 2023-06-26 13:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_act_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.TextField(default=uuid.UUID('f933f52b-c185-4aa6-b44f-c6621db0fd51'), max_length=500, verbose_name='act_token'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
