# Generated by Django 4.2.2 on 2023-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newuser_is_verified_alter_newuser_act_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.TextField(default='210221dd-2a9e-4403-b8f6-cf48b8c1be1e', max_length=500, verbose_name='act_token'),
        ),
    ]
