# Generated by Django 4.2.2 on 2023-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newuser_act_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.TextField(default='3c9380e8-750f-4e7d-b055-935ec387378c', max_length=500, verbose_name='act_token'),
        ),
    ]
