# Generated by Django 4.2.2 on 2023-07-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_act_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.TextField(default='33abb74f-c263-4984-b3c8-5fae98133e5a', max_length=500, verbose_name='act_token'),
        ),
    ]
