# Generated by Django 4.2.2 on 2023-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_newuser_act_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.TextField(default='<function uuid4 at 0x00000182798432E0>', max_length=500, verbose_name='act_token'),
        ),
    ]
