# Generated by Django 4.2.2 on 2023-07-01 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_newuser_act_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
