# Generated by Django 4.2.2 on 2023-07-03 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_newuser_act_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='act_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
