version: '3'
services:

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - api
      - frontend
      - db

  api:
    container_name: api-container
    build: ./api
    restart: always
    entrypoint: /docker_api/docker-entrypoint.sh
    command:
      #      - /bin/sh
      #      - -c
      - |
        python manage.py migrate
        python manage.py makemigrations musics
        python manage.py migrate

    # ref.
    # https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-createsuperuser
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin1234
      - DJANGO_SUPERUSER_EMAIL=mugiranezao@gmail.com

    ports:
      - "8000:8000"
    volumes:
      - api_data:/docker_api
    depends_on:
      - db

volumes:
  api_data:
  pgdata:
