# Generated by Django 3.2.7 on 2023-06-19 11:34

import ahome.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproperty',
            name='img',
            field=models.ImageField(upload_to=ahome.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='imageproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageProperties', to='ahome.propertie'),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='status',
            field=models.CharField(choices=[('for sale', 'for sale'), ('for rent', 'for rent')], default='for sale', max_length=250),
        ),
    ]
