# Generated by Django 3.2.6 on 2021-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0002_alter_propertie_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
