# Generated by Django 3.2.6 on 2021-08-13 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0003_propertie_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.FileField(null=True, upload_to='city_photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif'])]),
        ),
    ]
