# Generated by Django 3.2.6 on 2021-09-05 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0005_alter_city_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='presentation_image',
            field=models.ImageField(null=True, upload_to='property_photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'gif'])]),
        ),
    ]
