# Generated by Django 3.2.6 on 2021-09-05 17:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0006_propertie_presentation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertie',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertie', to='ahome.city'),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='presentation_image',
            field=models.ImageField(null=True, upload_to='property_photo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='propertie',
            name='status',
            field=models.CharField(choices=[('for sale', 'for Sale'), ('for rent', 'for rent')], default='for sale', max_length=250),
        ),
    ]
