# Generated by Django 3.2.6 on 2021-09-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahome', '0007_auto_20210905_1722'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planproperty',
            unique_together={('property', 'floorNum')},
        ),
    ]
