SIGN_MAIL = '<html> '\
            '<head><meta http-equiv="Content-Type" content="text/html; charset=us-ascii"></head>'\
            '<body> '\
            '<div style="background-color:#f5f5f6;margin:0">'\
            '<table style="sans-serif;font-size:14px;color:#5e5e5e;width:98%;max-width:600px;float:none;margin:0 auto" border="0" cellpadding="0" cellspacing="0" valign="top" align="left">    '\
            '<tbody>'\
            '<tr align="middle">       '\
            '<td style="padding-top:30px;padding-bottom:32px">'\
            '<img src="https://ok6static.oktacdn.com/assets/img/logos/okta-logo.1e146cad5713da744492be95eb0f7793.png" height="37"></td>   '\
            '</tr>  '\
            '<tr bgcolor="#ffffff">    '\
            '<td>'\
            '<table bgcolor="#ffffff" style="width:100%;line-height:20px;padding:32px;border:1px solid;border-color:#f0f0f0" cellpadding="0">      '\
            '<tbody>'\
            '<tr>   '\
            '<td style="color:#5e5e5e;font-size:22px;line-height:22px">Moongy - New sign-on detected for your Okta account</td> '\
            '</tr>  '\
            '<tr>'\
            '<td style="padding-top:24px">Hi Oscar,</td>'\
            '</tr>  '\
            '<tr>'\
            '<td style="padding-top:24px">Your Okta Account oscar.mugiraneza@agap2-it.fr was just used to sign-in from a new or unrecognized device, browser, or application.</td> '\
            '</tr>  '\
            '<tr>'\
            '<td style="padding-top:24px;font-size:18px;font-weight:600;color:#5e5e5e;line-height:24px">Sign-In Details</td>'\
            '</tr>  '\
            '<tr>'\
            '<td style="line-height:24px">CHROMIUM_EDGE - Windows 10 <br> Thu, May 4, 2023 <br> Noisiel, Seine-et-Marne, France <br> IP: 176.159.135.45</td>'\
            '</tr>  '\
            '<tr>'\
            '<td style="padding-top:24px;font-size:18px;font-weight:600;color:#5e5e5e;line-height:24px">Don t recognize this activity?</td>'\
            '</tr>  '\
            '<tr>'\
            '<td>Your account may have been compromised; we recommend reporting the suspicious activity to your organization.</td>      '\
            '</tr>  '\
            '<tr>'\
            '<td align="center" style="height:32px;padding-top:24px">  '\
            '<a href="{}" id="report-suspicious-activity" style="text-decoration:none">   '\
            '<span style="padding:9px 32px 7px 31px;border:1px solid;text-align:center;cursor:pointer;color:rgb( 255 , 255 , 255 );border-radius:3px;background-color:#1662dd;border-color:#1662dd;box-shadow:0 1px 0 #1662dd"> '\
            'Report Suspicious Activity'\
            '</span>'\
            '</a>'\
            '</td>  '\
            '</tr>  '\
            '<tr>'\
            '<td style="padding-top:24px"> '\
            'The security of your account is very important to us and we want to ensure that you are updated when important actions are taken.</td>'\
            '</tr>  '\
            '<tr>'\
            '<td style="padding-top:24px"> '\
            'We were unable to determine if you had previously signed in with this device before. This notification is common if you are signing in a new device, a new browser, have deleted your cookies or are accessing Okta in Incognito Mode.'\
            '</td>     '\
            '</tr>     '\
            '</tbody>  '\
            '</table>  '\
            '</td>     '\
            '</tr>     '\
            '<tr>      '\
            '<td style="font-size:12px;padding:16px 0 30px 50px;color:#999">    '\
            'This message was automatically generated by       '\
            '<a href="https://www.okta.com" style="color:rgb( 97 , 97 , 97 )">Okta</a>     '\
            'on Thu, May 4, 2023, at 01:50 PM (UTC). Replies are not monitored or answered.'\
            '</td>   '\
            '</tr>   '\
            '</tbody>'\
            '</table>'\
            '</div>  '\
            '</body> '\
            '</html>'







SIGN_MAIL_HEADER = "<!doctype html>" \
"<html>" \
"<head>" \
"    <style >" \
"#outlook a {" \
" padding: 0;" \
"}" \
"body {" \
" margin: 0;" \
" padding: 0;" \
" -webkit-text-size-adjust: 100%;" \
" -ms-text-size-adjust: 100%;" \
"}" \
"    </style>" \
"</head>"

SIGN_MAIL_BODY = "<body>" \
      "<a href='{}'" \
      "target='_blank'>Activer mon compte</a>" \
      "</body>"
SIGN_MAIL_FOOTER = "</html>"


def build_signin_mail(lien):
    return SIGN_MAIL.format(lien)
